#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🐶 Husky: Formateando y revisando el código del Frontend..."

# Entrar a la carpeta frontend y ejecutar los chequeos
cd frontend
pnpm run format
pnpm run lint

echo "✅ Todo en orden. ¡Commit autorizado!"